#!/usr/bin/env bash

COMMAND="$1"
shift

if [ "$COMMAND" == "" ]; then
    echo "Error: command is missing"
    echo "Possible commands: clean_tmp, reset, install, rights, composer-install, composer-update, install-admin"
    echo " unit-tests,  shell, shellroot"
    echo " ldapreset, ldapusers"
    exit 1;
fi

CONTAINER_PREFIX=jelix_auth

case $COMMAND in
    clean_tmp)
        docker exec -t -i ${CONTAINER_PREFIX}_php appctl.sh clean_tmp;;
    reset)
        docker exec -t -i ${CONTAINER_PREFIX}_php appctl.sh reset;;
    reset-setup)
        docker exec -t -i ${CONTAINER_PREFIX}_php appctl.sh reset
        docker exec -t -i ${CONTAINER_PREFIX}_php appctl.sh init-data
        ;;
    install)
        docker exec -t -i ${CONTAINER_PREFIX}_php appctl.sh install;;
    rights)
        docker exec -t -i ${CONTAINER_PREFIX}_php appctl.sh rights;;
    composer-install)
        docker exec -t -i ${CONTAINER_PREFIX}_php appctl.sh composer_install;;
    composer-update)
        docker exec -t -i ${CONTAINER_PREFIX}_php appctl.sh composer_update;;
    unit-tests)
        docker exec -t -i ${CONTAINER_PREFIX}_php appctl.sh unittests $@;;
    shell)
       docker exec -it --user userphp ${CONTAINER_PREFIX}_php  /bin/bash -l;;
    shellroot)
       docker exec -it ${CONTAINER_PREFIX}_php  /bin/bash  -l;;
    ldapreset)
      docker exec -it ${CONTAINER_PREFIX}_ldap /bin/ctl.sh reset
      ;;
    ldapusers)
       docker exec -it ${CONTAINER_PREFIX}_ldap /bin/ctl.sh showusers
       ;;
    ldapshell)
       docker exec -it ${CONTAINER_PREFIX}_ldap  /bin/bash -l
     ;;
    install-admin)
        docker exec -t -i ${CONTAINER_PREFIX}_php /bin/bash -c 'php test/testapp/console.php account:create admin admin@example.com' 
        docker exec -t -i ${CONTAINER_PREFIX}_php /bin/bash -c 'php test/testapp/console.php account:login:create -b daotablesqlite admin -p adminpass'
        docker exec -t -i ${CONTAINER_PREFIX}_php /bin/bash -c 'php test/testapp/console.php acl2user:register admin'
        docker exec -t -i ${CONTAINER_PREFIX}_php /bin/bash -c 'php test/testapp/console.php acl2user:addgroup admin admins'
        docker exec -t -i ${CONTAINER_PREFIX}_php /bin/bash -c 'php test/testapp/console.php acl2:add admins idpadmin.view'
        docker exec -t -i ${CONTAINER_PREFIX}_php /bin/bash -c 'php test/testapp/console.php acl2:add admins idpadmin.edit'
        echo "admin account created, login admin, password adminpass"
    ;;
    *)
        echo "wrong command"
        exit 2
        ;;
esac

